
function elementToDof= CreateElementToDof(elementList)
[elementToFace,NF]= CreateElementToFace(elementList);
elementToDof = [elementToFace(:,1), elementToFace(:,1)+NF,elementToFace(:,1)+2*NF,...
                elementToFace(:,2), elementToFace(:,2)+NF,elementToFace(:,2)+2*NF,...
                elementToFace(:,3), elementToFace(:,3)+NF,elementToFace(:,3)+2*NF,...
                elementToFace(:,4), elementToFace(:,4)+NF,elementToFace(:,4)+2*NF,...
                elementToFace(:,5), elementToFace(:,5)+NF,elementToFace(:,5)+2*NF,...
                elementToFace(:,6), elementToFace(:,6)+NF,elementToFace(:,6)+2*NF,...
                elementToFace(:,1)+3*NF, elementToFace(:,1)+4*NF,...
                elementToFace(:,2)+3*NF, elementToFace(:,2)+4*NF,...
                elementToFace(:,3)+3*NF, elementToFace(:,3)+4*NF,...
                elementToFace(:,4)+3*NF, elementToFace(:,4)+4*NF,...
                elementToFace(:,5)+3*NF, elementToFace(:,5)+4*NF,...
                elementToFace(:,6)+3*NF, elementToFace(:,6)+4*NF];


end